# Add 'label1' to any changes within 'example' folder or any subfolders
feature:
- any: ['.github/*']

# Add 'label2' to any file changes within 'example2' folder
defect: 
- any: ['vlocity/*']

# Add label3 to any change to .txt files within the entire repository. Quotation marks are required for the leading asterisk
# label3:
# - '**/*.txt'
