name: Pipeline Validation

# Workflow run name
run-name: Workflow run PR No - ${{ github.event.pull_request.number }} and PR title - ${{ github.event.pull_request.title }} by @${{ github.actor }}

# Workflow triggers
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths-ignore:
      - "**/README.md"

# Environment Variables
env:
  GIT_USER_NAME: github
  GIT_USER_EMAIL: githubactions@mydomain.com
  PR_NUMBER: ${{ github.event.number }}

jobs:
  installation_authenticate_validate:
    runs-on: ubuntu-latest
    environment: DEV-CI
    # Only executes next steps if Source branch name starts with develop
    if: ((startswith(github.head_ref,'feature') || startswith(github.head_ref,'defect')) && (github.event_name == 'pull_request'))
    steps:
      # Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Save PR number in PR_RUN text file
      - name: Save the PR number
        if: ${{github.event_name == 'pull_request'}}
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > pr_num.txt

      # Upload PR number
      - name: Upload Artifact PR number
        if: ${{github.event_name == 'pull_request'}}
        uses: actions/upload-artifact@v3
        with:
          name: pr_num
          path: ./pr_num.txt
          retention-days: 1

      # Save source branch of PR
      - name: Save the source branch of Pull request
        if: ${{github.event_name == 'pull_request'}}
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo $BRANCH_NAME > branch_name.txt

      # Upload the source branch of Pull request
      - name: Upload Artifact source branch of Pull request
        if: ${{github.event_name == 'pull_request'}}
        uses: actions/upload-artifact@v3
        with:
          name: branch_name
          path: ./branch_name.txt
          retention-days: 1

      # Checkout the current repository
      - name: Checkout Repository
        uses:  actions/checkout@v4

      # Checking out repo before installing Node
      - uses:  actions/checkout@v4
        name: Checkout Repository

      # Setup Node v18
      # - uses: actions/setup-node@v3
      #   name: Install Node v18
      #   with:
      #     node-version: "18"

      # Install the SFDX-CLI
      # - name: Install SFDX-CLI
      #   run: |
      #     wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      #     mkdir ~/sfdx && ls -la
      #     tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
      #     echo "$HOME/sfdx/bin" >> $GITHUB_PATH
      #     echo The PATH is $GITHUB_PATH
      #     ~/sfdx/bin/sfdx version

      # Install SF CLI V2
      - name: NPM Install SF CLI
        run: |
          node --version
          npm install @salesforce/cli --global

      # Verify
      - name: Verify Installation
        run: |
          sf --version
          sf commands
          sf whatsnew
