name: Pipeline PR Body - Get

# Workflow run name
run-name: Workflow run by @${{ github.actor }}

# Workflow triggers
on:
  workflow_run:
    workflows: [Pipeline PR Body]
    types: completed
#Jobs
jobs:
  pr_body:
    runs-on: ubuntu-latest
    environment: DEV-CI
    # Only executes next steps if Source branch name starts with feature or defect
    env:
      GH_TOKEN: ${{ secrets.V_METADATA_SEC }}
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: GH CLI
        run: |
          echo "GH CLI Version:"
          gh --version

      - name: Git fetch
        run:  |
          git fetch origin ${{github.head_ref}}
          git checkout ${{github.head_ref}}

      # Find
      - name: Issue last comment
        run: |
          echo "$(gh issue view 13 --json comments | jq -r '.comments[-1].body')" > comment.txt
          echo "Last issue thread is fetched"
          cat comment.txt

      # Update a comment PR Thread for Build-Success
      - name: Update Comment Thread - Delta Package Built Successfully
        run: |
          echo -e '------
            ### Artifact Links

            + Generated Delta Package [srcToDeploy.zip] :white_check_mark:' >> comment.txt
          gh issue comment 13 --edit-last -F comment.txt

      # Update a comment PR Thread for describe.log
      - name: Update Comment Thread - describe.log
        run: |
          echo "+ Generated [describe.log] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt

      # Update a comment PR Thread for NomenclatureReport.html
      - name: Update Comment Thread - NomenclatureReport
        run: |
          echo "+ Generated [NomenclatureReport.html] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt

      # Update a comment PR Thread for Validate.json
      - name: Update Comment Thread - Validate.json
        run: |
          echo "+ Generated [Validate.json] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt

      # Update a comment PR Thread for Deploy.json
      - name: Update Comment Thread - Deploy.json
        run: |
          echo "+ Generated [Deploy.json] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt

      # Update a comment PR Thread for sfdxScannerReport.html
      - name: Update Comment Thread - sfdxScannerReport.html
        run: |
          echo "+ Generated [sfdxScannerReport.html] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt
      
      # Update a comment PR Thread for VlocityBuildErrors.log
      - name: Update Comment Thread - VlocityBuildErrors.log
        run: |
          echo "+ Generated [VlocityBuildError.log] :white_check_mark:" >> comments.txt
          gh issue comment 13 --edit-last -F comment.txt