name: Pipeline PR Body - Get

# Workflow run name
run-name: Workflow run by @${{ github.actor }}

# Workflow triggers
on:
  workflow_run:
    workflows: [Pipeline PR Body]
    types: completed
#Jobs
jobs:
  pr_body:
    runs-on: ubuntu-latest
    environment: DEV-CI
    # Only executes next steps if Source branch name starts with feature or defect
    env:
      GH_TOKEN: ${{ secrets.V_METADATA_SEC }}
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: GH CLI
        run: |
          echo "GH CLI Version:"
          gh --version

      # git fetch
      - name: Git fetch
        run:  |
          git fetch origin ${{github.head_ref}}
          git checkout ${{github.head_ref}}

      # Find
      - name: Issue last comment
        run: |
          echo "+ From Child workflow" >> comment.txt
          gh issue comment --edit-last -F comment.txt

      #     # echo '${{github.event.issue_comments.comment.body}}' > simple2.txt
      #     # cat simple2.txt
      #     # gh pr view --comments --json body | jq -r '.[0].body' > simple.txt
      #     # cat simple.txt

      # Update comment in PR Thread: OS dependencies installed
      - name: Update Comment Thread - Dependencies installed
        run: |
          echo "+ All dependencies installed" >> comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --edit-last -F comment.txt 

      # Update comment in PR Thread: Salesforce-Auth-Success
      - name: Update Comment Thread - Salesforce authentication Successful
        run: |
          echo "+ Successful Salesforce authentication :white_check_mark:" >> comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --edit-last -F comment.txt