name: Pipeline PR Body

# Workflow run name
run-name: Workflow run PR No - ${{ github.event.pull_request.number }} and PR title - ${{ github.event.pull_request.title }} by @${{ github.actor }}

# Workflow triggers
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths-ignore:
      - "**/README.md"
#Jobs Test
jobs:
  pr_body:
    runs-on: ubuntu-latest
    environment: DEV-CI
    # Only executes next steps if Source branch name starts with feature or defect
    if: ((github.event_name == 'pull_request'))
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./ORGS/
          mode: DEV-CI

      - name: print env variables
        run: |
          echo ${{env.SF_User}}
          cat ORGS/.env.DEV-CI

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.SF_User }}"
      # # Find unit tests defined in the PR Body version 2
      # - name: Find Unit Tests In Pull Request Body v2
      #   id: regex-match
      #   run: |
      #     echo '${{github.event.pull_request.body}}' > pullRequestBody.txt
      #     python3 ./readPRBody.py -s pullRequestBody.txt
      # # Print ENV PR_TESTS
      # - name: Echo PR_TESTS
      #   run: echo ${{env.PR_TESTS}}